#!/usr/bin/env python

import env

import ui.add_menu_entry as add_menu_entry

##############################################################################

ctx = env.create(__file__)
if not (ctx.read_opts()):
    ctx.fatal("arguments required")

ctx.exec(add_menu_entry)
if ctx.NO_MENU:
    ctx.fatal("no menu entry specified")

##############################################################################
