#!/usr/bin/env python

import env

import ui.schema_parse_as_entity_collection as schema_parse_as_entity_collection
import ui.html_generate_enum__ru_ as html_generate_enum__ru_
import ui.ts_generate_enum__ru_ as ts_generate_enum__ru_
import ui.css_copy_enum__ru_ as css_copy_enum__ru_
import ui.ts_generate_model_crud as ts_generate_model_crud
import ui.ts_generate_service_crud as ts_generate_service_crud
import ui.ts_generate_routes as ts_generate_routes
import ui.ts_merge_app_routes as ts_merge_app_routes
import ui.add_menu_entry as add_menu_entry
import app.project_show_completed_tasks as project_show_completed_tasks
import app.project_check_user_actions as project_check_user_actions

import app.project_summary_entity_names as project_summary_entity_names
import app.project_summary_analysis as project_summary_analysis
import app.project_summary_sql as project_summary_sql

##############################################################################

ctx = env.create(__file__)
ctx.set_entity_names_path_snake()
ctx.exec(schema_parse_as_entity_collection)
ctx.exec(html_generate_enum__ru_)
ctx.exec(ts_generate_enum__ru_)
ctx.exec(css_copy_enum__ru_)
ctx.exec(ts_generate_model_crud)
ctx.exec(ts_generate_service_crud)
ctx.exec(ts_generate_routes)
ctx.exec(ts_merge_app_routes)
ctx.exec(add_menu_entry)

ctx.set_opt("--quiet", False)
ctx.exec(project_show_completed_tasks)
ctx.exec(project_check_user_actions)

##############################################################################

# ctx.exec(project_summary_entity_names)
# ctx.exec(project_summary_analysis)
# ctx.exec(project_summary_sql)
