#!/usr/bin/env bash

(return 0 2>/dev/null) || { echo "$0: must be sourced"; exit 1; }

APPGEN_HOME=$(dirname "${BASH_SOURCE-$0}") >/dev/null 2>&1
[ -z "${APPGEN_HOME}" ] && APPGEN_HOME=$(dirname ${(%):-%x})
export __APPGEN_HOME__="${APPGEN_HOME}"
export __APPGEN_PROFILE_FE__="ng-20.0.3-mui"
export __APPGEN_PROFILE_FE_PATH__="${__APPGEN_HOME__}/${__APPGEN_PROFILE_FE__}"
export __APPGEN_PROFILE_BE__="express-js-postgres"
export __APPGEN_PROFILE_BE_PATH__="${__APPGEN_HOME__}/${__APPGEN_PROFILE_BE__}"

[ ! -d "${__APPGEN_PROFILE_FE_PATH__}" ] && echo "INVALID PATH: ${__APPGEN_PROFILE_FE_PATH__}" && return
[ ! -d "${__APPGEN_PROFILE_BE_PATH__}" ] && echo "INVALID PATH: ${__APPGEN_PROFILE_BE_PATH__}" && return

export PATH="${__APPGEN_HOME__}:${__APPGEN_PROFILE_BE_PATH__}:${__APPGEN_PROFILE_FE_PATH__}:${PATH}"
