#!/usr/bin/env bash

(return 0 2>/dev/null) || { echo "$0: must be sourced"; exit 1; }

DISTRO_NAME=$(uname -s | sed 's/-.*//')
export PYTHON_ENVIRONMENT="venv-$DISTRO_NAME"
export PYTHON_CMD=

python_activate() { 
   if ! [ -d "./$PYTHON_ENVIRONMENT" ]; then
    echo "creating environment: $PYTHON_ENVIRONMENT using $PYTHON_CMD -m venv ./$PYTHON_ENVIRONMENT"
    $PYTHON_CMD -m venv "./$PYTHON_ENVIRONMENT"
  fi

  if [ -d "./$PYTHON_ENVIRONMENT" ]; then
    echo "found environment: $PYTHON_ENVIRONMENT"
  fi

  # windows (msys, git-bash)
  if [ -e "./$PYTHON_ENVIRONMENT/Scripts/activate" ]; then
    echo "activating environment: ./$PYTHON_ENVIRONMENT/Scripts/activate"
    # shellcheck disable=SC1090
    . "./$PYTHON_ENVIRONMENT/Scripts/activate"
    python -m pip install --upgrade pip

    if [ -e requirements.txt ]; then
      echo installing packages using requirements.txt
      pip install -r requirements.txt
    fi
  fi

  # Linux, MacOS, ...
  if [ -e "./$PYTHON_ENVIRONMENT/bin/activate" ]; then
    echo "activating environment: ./$PYTHON_ENVIRONMENT/bin/activate"
    # shellcheck disable=SC1090
    . "./$PYTHON_ENVIRONMENT/bin/activate"
    python -m pip install --upgrade pip

    if [ -e requirements.txt ]; then
      echo installing packages using requirements.txt
      pip install -r requirements.txt
    fi
  fi
}

echo '- configuring app generation environment'

if [ -z "$PYTHON_CMD" ] && [ "$(command -v py)" ]; then
  export PYTHON_CMD=py
fi

if [ -z "$PYTHON_CMD" ] && [ "$(command -v python)" ]; then
  export PYTHON_CMD=python
fi

if [ -z "$PYTHON_CMD" ] && [ "$(command -v python3)" ]; then
  export PYTHON_CMD=python3
fi

if [ -z "$PYTHON_CMD" ] && [ "$(command -v python2)" ]; then
  export PYTHON_CMD=python2
fi

[ -z $PYTHON_CMD ] && echo 'python not found - cannot set environment' && return 1

THIS_DIR=${PWD}
cd "${__APPGEN_HOME__}" || return
python_activate
cd "$THIS_DIR" || return

echo "- app generation templates"
echo "frontend: ${__APPGEN_PROFILE_FE_PATH__}"
echo "backend:  ${__APPGEN_PROFILE_BE_PATH__}"
