#!/usr/bin/env python

import set_paths
import ng_20_0_3_mui.frontend_context as context
import ng_20_0_3_mui.tasks.add_menu_entry as add_menu_entry

##############################################################################

ctx = context.create(__file__)
if not (ctx.read_opts()):
    ctx.fatal("arguments required")

ctx.exec(add_menu_entry)
if ctx.NO_MENU:
    ctx.fatal("no menu entry specified")

##############################################################################
