#!/usr/bin/env python

import set_paths
import ng_20_0_3_mui.frontend_context as context
import ng_20_0_3_mui.tasks.remove_menu_entry as remove_menu_entry

##############################################################################

ctx = frontend_context.create(__file__)
if not (ctx.read_opts()):
    ctx.fatal("arguments required")

ctx.exec(remove_menu_entry)
if ctx.NO_MENU:
    ctx.fatal("no menu entry specified")

##############################################################################
