#!/usr/bin/env python

import set_paths
import ng_20_0_3_mui.frontend_context as context
import ng_20_0_3_mui.tasks.copy_app_component as copy_app_component
import ng_20_0_3_mui.tasks.copy_home_page_component as copy_home_page_component
import ng_20_0_3_mui.tasks.copy_alert_component as copy_alert_component
import ng_20_0_3_mui.tasks.copy_dockerfile as copy_dockerfile

##############################################################################

ctx = context.create(__file__)
ctx.exec(copy_app_component)
ctx.exec(copy_home_page_component)
ctx.exec(copy_alert_component)
ctx.exec(copy_dockerfile)

##############################################################################
