#!/usr/bin/env bash

FATAL_FILE="./fatal.txt"
[ -f $FATAL_FILE ] && cat $FATAL_FILE && exit 1

mkdir -p ./frontend
cd ./frontend || exit

[ -d node_modules ] && echo "$0: found node_modules, skipping" && exit

mise trust ./mise.toml
mise install
mise r install-ng
mise r ng new frontend --directory ./ --defaults --skip-git
mise r ng add @angular/material --defaults --skip-confirmation

# npm add prettier -D # works, but requires "npx prettier --write ." at end of configuration
mise r npm pkg set scripts.start="ng serve --host 0.0.0.0"
mise r npm i @angular/animations --legacy-peer-deps

# hack for line endings on windows
files=".editorconfig .gitignore README.md angular.json tsconfig.app.json tsconfig.json tsconfig.spec.json src/index.html src/main.ts src/styles.css"
for file in ${files}; do
    dos2unix "${file}"
done
