#!/usr/bin/env python

import tasks.component.component_context as component_context
import tasks.component.url_parse_entity_names as url_parse_entity_names
import tasks.component.ensure_entity_is_enum as ensure_entity_is_enum
import tasks.component.url_parse_result_as_entity_collection as url_parse_result_as_entity_collection

import tasks.component.html_generate_enum__ru_ as html_generate_enum__ru_
import tasks.component.ts_generate_enum__ru_ as ts_generate_enum__ru_
import tasks.component.css_copy_enum__ru_ as css_copy_enum__ru_

import tasks.component.ts_generate_model_crud as ts_generate_model_crud
import tasks.component.ts_generate_service_crud as ts_generate_service_crud

import tasks.component.ts_generate_routes as ts_generate_routes
import tasks.component.ts_merge_app_routes as ts_merge_app_routes
import tasks.app.add_menu_entry as add_menu_entry

import project.tasks.project_show_completed_tasks as project_show_completed_tasks
import project.tasks.project_check_user_actions as project_check_user_actions

import project.tasks.project_summary_entity_names as project_summary_entity_names
import project.tasks.project_summary_analysis as project_summary_analysis
import project.tasks.project_summary_sql as project_summary_sql

##############################################################################

ctx = component_context.create(__file__)
ctx.exec(url_parse_entity_names)
ctx.exec(ensure_entity_is_enum)
ctx.exec(url_parse_result_as_entity_collection)

ctx.exec(html_generate_enum__ru_)
ctx.exec(ts_generate_enum__ru_)
ctx.exec(css_copy_enum__ru_)

ctx.exec(ts_generate_model_crud)
ctx.exec(ts_generate_service_crud)

ctx.exec(ts_generate_routes)
ctx.exec(ts_merge_app_routes)
ctx.exec(add_menu_entry)

ctx.set_opt("--quiet", False)
ctx.exec(project_show_completed_tasks)
ctx.exec(project_check_user_actions)

##############################################################################

# ctx.exec(project_summary_entity_names)
# ctx.exec(project_summary_analysis)
# ctx.exec(project_summary_sql)
