#!/usr/bin/env python

import tasks.frontend_context as frontend_context
import tasks.app.copy_app_component as copy_app_component
import tasks.app.copy_home_page_component as copy_home_page_component
import tasks.app.copy_alert_component as copy_alert_component
import tasks.app.copy_dockerfile as copy_dockerfile

##############################################################################

ctx = frontend_context.create(__file__)
ctx.exec(copy_app_component)
ctx.exec(copy_home_page_component)
ctx.exec(copy_alert_component)
ctx.exec(copy_dockerfile)

##############################################################################
