#!/usr/bin/env bash

FATAL_FILE="./appgen-fatal.txt"
[ -f $FATAL_FILE ] && cat $FATAL_FILE && exit 1

SCRIPTS_DIR=$(dirname "${BASH_SOURCE-$0}") >/dev/null 2>&1
DIR_NAME=${PWD##*/}

cp "$SCRIPTS_DIR"/mise.toml .
mise trust ./mise.toml
mise install
mise r install-ng
mise r ng new "$DIR_NAME" --directory ./ --defaults --skip-git
mise r ng add @angular/material --defaults --skip-confirmation

# npm add prettier -D # works, but requires "npx prettier --write ." at end of configuration
mise r npm pkg set scripts.start="ng serve --host 0.0.0.0"
mise r npm install @angular/animations --legacy-peer-deps

# hack for line endings on windows
# files=".editorconfig .gitignore README.md angular.json tsconfig.app.json tsconfig.json tsconfig.spec.json src/index.html src/main.ts src/styles.css"
# for file in ${files}; do
#     dos2unix "${file}"
# done
