#!/usr/bin/env python

API_UUID = "30125261-A5CA-48E4-997E-3935C07BED5D"

import tasks.component.component_context as component_context
import tasks.component.schema_parse_as_entity_collection as schema_parse_as_entity_collection

import tasks.component.ts_generate_model_crud as ts_generate_model_crud
import tasks.component.ts_generate_view_be4fe as ts_generate_view_be4fe
import tasks.component.ts_generate_viewmodel_be4fe as ts_generate_viewmodel_be4fe

import tasks.component.html_generate_table_be4fe_paged as html_generate_table_be4fe_paged
import tasks.component.ts_generate_table_be4fe_paged as ts_generate_table_be4fe_paged
import tasks.component.css_copy_xxxx_crud as css_copy_xxxx_crud

import tasks.component.html_generate_table_be4fe_form as html_generate_table_be4fe_form
import tasks.component.ts_generate_xxxx_crud_form as ts_generate_xxxx_crud_form
import tasks.component.css_copy_xxxx_crud_form as css_copy_xxxx_crud_form

import tasks.component.ts_generate_api_model_be4fe_paged as ts_generate_api_model_be4fe_paged
import tasks.component.ts_generate_service_be4fe_paged as ts_generate_service_be4fe_paged

import tasks.component.ts_generate_routes as ts_generate_routes
import tasks.component.ts_merge_app_routes as ts_merge_app_routes
import tasks.app.add_menu_entry as add_menu_entry

import project.tasks.project_show_completed_tasks as project_show_completed_tasks
import project.tasks.project_check_user_actions as project_check_user_actions

import project.tasks.project_summary_entity_names as project_summary_entity_names
import project.tasks.project_summary_analysis as project_summary_analysis
import project.tasks.project_summary_sql as project_summary_sql

##############################################################################

ctx = component_context.create(__file__)
ctx.API_UUID = API_UUID
ctx.exec(schema_parse_as_entity_collection)

ctx.exec(ts_generate_model_crud)
ctx.exec(ts_generate_view_be4fe)
ctx.exec(ts_generate_viewmodel_be4fe)

ctx.exec(html_generate_table_be4fe_paged)
ctx.exec(ts_generate_table_be4fe_paged)
ctx.exec(css_copy_xxxx_crud)

ctx.exec(ts_generate_xxxx_crud_form)
ctx.exec(html_generate_table_be4fe_form)
ctx.exec(css_copy_xxxx_crud_form)

ctx.exec(ts_generate_api_model_be4fe_paged)
ctx.exec(ts_generate_service_be4fe_paged)

ctx.exec(ts_generate_routes)
ctx.exec(ts_merge_app_routes)
ctx.exec(add_menu_entry)

ctx.set_opt("--quiet", False)
ctx.exec(project_show_completed_tasks)
ctx.exec(project_check_user_actions)

##############################################################################

# ctx.exec(project_summary_entity_names)
# ctx.exec(project_summary_analysis)
# ctx.exec(project_summary_sql)
