#!/usr/bin/env python

import tasks.backend_context as backend_context
import tasks.api.api_copy_files as api_copy_files

##############################################################################

ctx = backend_context.create_for_init(__file__)
ctx.exec(api_copy_files)

##############################################################################
