#!/usr/bin/env bash

FATAL_FILE="./appgen-fatal.txt"
[ -f $FATAL_FILE ] && cat $FATAL_FILE && exit 1

SCRIPTS_DIR=$(dirname "${BASH_SOURCE-$0}") >/dev/null 2>&1

cp "$SCRIPTS_DIR"/mise.toml .
mise trust ./mise.toml 
mise install

mise r npm init -y
mise r npm pkg set main="./src/index.js"
mise r npm pkg set scripts.api="nodemon ./src/index.js"
mise r npm pkg set scripts.docs="node ./src/swagger-autogen.js"
mise r npm pkg set scripts.start="npm run docs && npm run api"

mise r npm install --verbose express
mise r npm install --verbose swagger-ui-express
mise r npm install --verbose swagger-autogen
mise r npm install --verbose pg
mise r npm install --verbose cors

mise r npm install --verbose -D nodemon

echo PORT=3000 > .env

mkdir src
echo "console.log('Hello');" > ./src/index.js
