#!/usr/bin/env python

import pandas as pd
import shutil as sh
import os.path
import sys
import requests
import json
import re

if len(sys.argv) <= 1:
    print("url required")
    exit()

entity_url = sys.argv[1]

try:
    response = requests.get(entity_url)
    response_json = response.json()
    entity_pascal = entity_url.split("/")[-1]
except Exception as e:
    print("reading url failed")
    print(f"FATAL: {e}")
    exit()


def banner(message):
    print("-" * 80)
    print(message)


entity_pascal_spaced = re.findall(r"[A-Z][^A-Z]*", entity_pascal)
entity_pascal_spaced = " ".join(entity_pascal_spaced)
entity_lower_spaced = entity_pascal_spaced.lower()
entity_snake = entity_lower_spaced.replace(" ", "_").lower()
entity_snake_ucase = entity_snake.upper()
entity_kebab = entity_snake.replace("_", "-")
entity_camel = entity_pascal[0].lower() + entity_pascal[1:]

TEMPLATE_PATH = f'{os.environ["__APPGEN_FE_PATH__"]}/templates/component'
ALERT_PATH = f'{os.environ["__APPGEN_FE_PATH__"]}/templates/alert'
FRONTEND_PATH = "./presentation"
COMPONENT_PATH = f"{FRONTEND_PATH}/src/pages/{entity_kebab}"

banner(f"component: {COMPONENT_PATH}")

expected_entity_id = entity_snake + "_id"

# expects a response shape with an array of result
item = response_json["result"][0]
keys = list(item.keys())
entity_id = keys[0]

if entity_id != expected_entity_id:
    ctx.error(f"{entity_id} != {expected_entity_id}")
    exit()

# create component folder
try:
    os.mkdir(COMPONENT_PATH)
    print(f"folder: '{COMPONENT_PATH}' created successfully.")
except FileExistsError:
    print(f"folder: '{COMPONENT_PATH}' already exists.")
except PermissionError:
    print(f"unable to create folder: '{COMPONENT_PATH}'.")
except Exception as e:
    print(f"FATAL: {e}")
    exit()


def save_data(filepath, data):
    print(f"{filepath}")
    with open(filepath, "w", newline="\n") as file:
        file.write(data)


def generateDto():
    dto = f"export interface {entity_pascal} " + "{\n"
    for idx in range(len(keys) + 1):
        if idx >= len(keys):  # terminal actions
            dto = dto + "};"
            break  # prevent out-of-bounds access
        key = keys[idx]
        if key.endswith("_id"):
            dto = dto + f"    {key}: number," + "\n"
        else:
            dto = dto + f"    {key}: string," + "\n"
    save_data(f"{COMPONENT_PATH}/{entity_kebab}.ts", dto)


def generateEnumPageHtml():

    tbl_keys = ""
    tbl_vals = ""
    create = ""
    indent = "                "

    for idx in range(len(keys) + 1):

        if idx == 0:  # skip id column
            continue

        if idx >= len(keys):  # terminal actions
            tbl_keys = tbl_keys + indent + "<th>Action</th>"
            create = (
                create
                + indent
                + '<td><button (click)="create()" [disabled]="isNullOrEmpty(newItem)">Add</button></td>'
            )
            break  # prevent out-of-bounds access

        key = keys[idx]

        # assume keys snake-cased
        column_name = key.removesuffix("_enum").replace("_", " ").title()

        tbl_key = f"<th>{column_name}</th>" + "\n"
        control = (
            f'<td><input type="text" [(ngModel)]="__ENTITY_CAMEL__Collection[idx].{key}" name="{key}_'
            + '{{idx}}" /></td>\n'
        )

        if idx == len(keys) - 1:
            tbl_keys = tbl_keys + tbl_key

            tbl_vals = tbl_vals + control
            tbl_vals = (
                tbl_vals
                + '                @if (idx < __ENTITY_CAMEL__Collection.length -1) { <td><button (click)="update(item)">Save</button>'
                + "\n"
            )
            tbl_vals = tbl_vals + "                    } @else {\n"
            tbl_vals = (
                tbl_vals
                + '                    <td><button (click)="update(item)">Save</button><nz-divider nzType="vertical"></nz-divider><button\n'
            )
            tbl_vals = (
                tbl_vals
                + '                            (click)="delete(item)">Delete</button>\n'
            )
            tbl_vals = tbl_vals + "                        }"
        else:
            tbl_keys = tbl_keys + tbl_key
            tbl_vals = tbl_vals + control

        if idx:
            create = (
                create
                + f'<td><input [(ngModel)]="newItem.{key}" name="newItem.{key}" /></td>'
                + "\n"
            )

    with open(f"{TEMPLATE_PATH}/enum-page-template.component.html", "r") as file:
        filedata = file.read()
    filedata = filedata.replace("__TBL_KEYS__", tbl_keys)
    filedata = filedata.replace("__TBL_VALS__", tbl_vals)
    filedata = filedata.replace("__CREATE__", create)
    filedata = filedata.replace("__ENTITY_PASCAL__", entity_pascal)
    filedata = filedata.replace("__ENTITY_CAMEL__", entity_camel)
    filedata = filedata.replace("__ENTITY_KEBAB__", entity_kebab)
    filedata = filedata.replace("__ENTITY_ID__", entity_id)
    save_data(f"{COMPONENT_PATH}/{entity_kebab}.component.html", filedata)


def generateTablePageHtml():

    tbl_keys = ""
    tbl_vals = ""
    create = ""
    indent = "                "

    for idx in range(len(keys) + 1):

        if idx == 0:  # skip id column
            continue

        if idx >= len(keys):  # terminal actions
            tbl_keys = tbl_keys + indent + "<th nzRight>Action</th>"
            create = (
                create
                + '<td nzRight><button (click)="create()" [disabled]="isNullOrEmpty(newItem)">Add</button></td>'
            )
            break  # prevent out-of-bounds access

        key = keys[idx]

        # assume keys snake-cased
        column_name = key.removesuffix("_enum").replace("_", " ").title()

        tbl_key = f"<th>{column_name}</th>" + "\n"

        if key.endswith("_enum"):
            with open(
                f"{TEMPLATE_PATH}/enum-control-template.component.html", "r"
            ) as file:
                control = file.read()
            create = create + control
            pascal_type = key.replace("_", " ").title().replace(" ", "")
            camel_type = pascal_type[0].lower() + pascal_type[1:]
            collection_name = f"{camel_type}Collection"
            control = control.replace("__COLLECTION_NAME__", collection_name)
            control = control.replace("__KEY__", key)
            enum_item = f"{key}_item"
            control = control.replace("__ENUM__ITEM__", enum_item)
            control_coll = control.splitlines()
            control = ("\n            ").join(map(str, control_coll)) + "\n"
            create = create.replace("__COLLECTION_NAME__", collection_name)
        else:
            control = (
                f'<td><input type="text" [(ngModel)]="__ENTITY_CAMEL__Collection[idx].{key}" name="{key}_'
                + '{{idx}}" /></td>\n'
            )
            create = (
                create
                + f'<td><input type="text" [(ngModel)]="newItem.{key}" name="newItem.{key}" /></td>\n'
            )

        create = create.replace("item.__KEY__", "newItem.__KEY__")
        create = create.replace(
            "__ENTITY_CAMEL__Collection[idx].__KEY__", "newItem.__KEY__"
        )
        create = create.replace("__KEY__{{idx}}", "newItem.__KEY__")
        create = create.replace("__ENUM__ITEM__", "item")
        create = create.replace("__KEY__", key)

        if idx == len(keys) - 1:  # last column
            tbl_keys = tbl_keys + indent + tbl_key
            tbl_vals = tbl_vals + indent + control
            tbl_vals = (
                tbl_vals
                + indent
                + '<td nzRight><button (click)="update(item)">Save</button><nz-divider nzType="vertical"></nz-divider><button\n'
            )
            tbl_vals = tbl_vals + indent + '(click)="delete(item)">Delete</button>'
            control = control.replace("<td>", "<td nzRight>")

        else:
            if idx == 1:  # first column
                tbl_keys = tbl_keys + f"<th nzLeft>{column_name}</th>" + "\n"
                control = control.replace("<td>", "<td nzLeft>")
                create = create.replace("<td>", "<td nzLeft>")
                tbl_vals = tbl_vals + control
            else:
                tbl_keys = tbl_keys + indent + tbl_key
                tbl_vals = tbl_vals + indent + control

    with open(f"{TEMPLATE_PATH}/table-page-template.component.html", "r") as file:
        filedata = file.read()
    filedata = filedata.replace("__TBL_KEYS__", tbl_keys)
    filedata = filedata.replace("__TBL_VALS__", tbl_vals)
    filedata = filedata.replace("__CREATE__", create)
    filedata = filedata.replace("__ENTITY_PASCAL__", entity_pascal)
    filedata = filedata.replace("__ENTITY_CAMEL__", entity_camel)
    filedata = filedata.replace("__ENTITY_KEBAB__", entity_kebab)
    filedata = filedata.replace("__ENTITY_ID__", entity_id)
    save_data(f"{COMPONENT_PATH}/{entity_kebab}.component.html", filedata)


def generateEnumPageComponent():
    with open(f"{TEMPLATE_PATH}/enum-page-template.component.ts", "r") as file:
        filedata = file.read()
    filedata = filedata.replace("__ENTITY_PASCAL__", entity_pascal)
    filedata = filedata.replace("__ENTITY_CAMEL__", entity_camel)
    filedata = filedata.replace("__ENTITY_KEBAB__", entity_kebab)
    filedata = filedata.replace("__ENTITY_ID__", entity_id)
    save_data(f"{COMPONENT_PATH}/{entity_kebab}.component.ts", filedata)


def generateTablePageComponent():

    indent4 = "    "
    indent8 = "        "
    table_page_imports = []
    collections_declarations = []
    injected_services = []
    collections_init = []
    services_read = []

    for idx, key in enumerate(keys):
        if key.endswith("_enum"):
            PascalType = key.replace("_", " ").title().replace(" ", "")
            KebabType = key.replace("_", "-")
            camelType = PascalType[0].lower() + PascalType[1:]

            collection_name = f"{camelType}Collection"
            collection = f"{collection_name}: {PascalType}[] = [];"
            if len(collections_declarations):
                collections_declarations.append(indent4 + collection)
            else:
                collections_declarations.append(collection)

            table_page_imports.append(
                "import { " + PascalType + " } from " + f"'../{KebabType}/{KebabType}';"
            )
            table_page_imports.append(
                "import { "
                + PascalType
                + "Service } from "
                + f"'../{KebabType}/{KebabType}.service';"
            )

            service_name = f"{camelType}Service"
            service_inject = f"public {service_name}: {PascalType}Service,"
            if len(injected_services):
                injected_services.append(indent8 + service_inject)
            else:
                injected_services.append(service_inject)

            service_read_function = f"{camelType}Read"
            fill_collection = f"this.{service_read_function}();"
            if len(collections_init):
                collections_init.append(indent8 + fill_collection)
            else:
                collections_init.append(fill_collection)

            with open(f"{TEMPLATE_PATH}/read-function.template.ts", "r") as file:
                read_function = file.read()

            read_function = read_function.replace(
                "__SERVICE_READ_FUNCTION__", service_read_function
            )
            read_function = read_function.replace("__SERVICE_NAME__", service_name)
            read_function = read_function.replace(
                "__COLLECTION_NAME__", collection_name
            )
            read_function_coll = read_function.splitlines()

            if len(services_read):
                read_function_coll[0] = indent4 + read_function_coll[0]
                services_read.append(
                    ("\n" + indent4).join(map(str, read_function_coll)) + "\n"
                )
            else:
                services_read.append(
                    ("\n" + indent4).join(map(str, read_function_coll)) + "\n"
                )

    with open(f"{TEMPLATE_PATH}/table-page-template.component.ts", "r") as file:
        filedata = file.read()
    filedata = filedata.replace("__ENTITY_PASCAL__", entity_pascal)
    filedata = filedata.replace("__ENTITY_CAMEL__", entity_camel)
    filedata = filedata.replace("__ENTITY_KEBAB__", entity_kebab)
    filedata = filedata.replace("__ENTITY_ID__", entity_id)

    filedata = filedata.replace(
        "__TABLE_PAGE_IMPORTS__", "\n".join(map(str, table_page_imports))
    )
    filedata = filedata.replace(
        "__COLLECTIONS_DECLARATIONS__", "\n".join(map(str, collections_declarations))
    )
    filedata = filedata.replace(
        "__INJECTED_SERVICES__", "\n".join(map(str, injected_services))
    )
    filedata = filedata.replace(
        "__COLLECTIONS_INIT__", "\n".join(map(str, collections_init))
    )
    filedata = filedata.replace("__SERVICES_READ__", "\n".join(map(str, services_read)))

    save_data(f"{COMPONENT_PATH}/{entity_kebab}.component.ts", filedata)


# generate html pages
is_enum_entity = entity_snake.endswith("_enum")
if is_enum_entity:
    banner("generate html page - enum page entity")
    generateEnumPageHtml()
    generateEnumPageComponent()
    sh.copyfile(
        f"{TEMPLATE_PATH}/enum-page-template.component.css",
        f"{COMPONENT_PATH}/{entity_kebab}.component.css",
    )
else:
    banner("generate html page - table page entity")
    generateTablePageHtml()
    generateTablePageComponent()
    sh.copyfile(
        f"{TEMPLATE_PATH}/table-page-template.component.css",
        f"{COMPONENT_PATH}/{entity_kebab}.component.css",
    )

banner("generate dto")
generateDto()

banner("generate service")
# generate service
with open(f"{TEMPLATE_PATH}/template.service.ts", "r") as file:
    filedata = file.read()
filedata = filedata.replace("__ENTITY_PASCAL__", entity_pascal)
filedata = filedata.replace("__ENTITY_KEBAB__", entity_kebab)
filedata = filedata.replace("__ENTITY_ID__", entity_id)
filedata = filedata.replace("__ENTITY_URL__", entity_url)
save_data(f"{COMPONENT_PATH}/{entity_kebab}.service.ts", filedata)

banner("generate routes")
# generate routes
with open(f"{TEMPLATE_PATH}/template.routes.ts", "r") as file:
    filedata = file.read()
filedata = filedata.replace("__ENTITY_PASCAL__", entity_pascal)
filedata = filedata.replace("__ENTITY_KEBAB__", entity_kebab)
filedata = filedata.replace("__ENTITY_SNAKE_UCASE__", entity_snake_ucase)
save_data(f"{COMPONENT_PATH}/{entity_kebab}.routes.ts", filedata)

banner("insert routes into app.routes.ts")
# insert routes into app.routes.ts
app_routes_fp = f"{APP_APP_PATH}/app.routes.ts"
with open(app_routes_fp, "r") as file:
    filedata = file.read()
if f"{entity_snake_ucase}_ROUTES" in filedata:
    print(f"found {entity_snake_ucase}_ROUTES in {app_routes_fp}, skipping")
else:
    print(f"inserting {entity_snake_ucase}_ROUTES in {app_routes_fp}")
    cut_idx = filedata.rfind("];")
    if cut_idx:
        filedata = filedata[:cut_idx]
    route = (
        "    , {"
        + f" path: '{entity_kebab}', loadChildren: () => import('./pages/{entity_kebab}/{entity_kebab}.routes').then(m => m.{entity_snake_ucase}_ROUTES)"
        + " }"
    )
    filedata = filedata + route + "\n];"
with open(app_routes_fp, "w", newline="\n") as file:
    file.write(filedata)

banner("insert page into app.component.html")
# insert page into app.component.html
app_component_fp = f"{APP_APP_PATH}/app.component.html"
with open(app_component_fp, "r") as file:
    filedata = file.read()
router_link = f'<a routerLink="/{entity_kebab}">'
if router_link in filedata:
    print(f"found {router_link} in {app_component_fp}")
else:
    print("insert:")
    print("<li nz-menu-item nzMatchRouter>")
    print(f"    {router_link}{entity_pascal}</a>")
    print("</li>")
    print(f"into {app_component_fp}")
