#!/usr/bin/env bash

appgen-info || exit

try () {
    "$@" || return 1
}

# 2-phase creation/customization: part 2
export APPGEN_PROJECT_NAME=${PWD##*/}
echo "NAME=${APPGEN_PROJECT_NAME}" > ./docker/.env
chmod +x ./docker/*
chmod +x ./tmux/*

echo "echo ${APPGEN_PROJECT_NAME}" > _app_name
chmod +x ./_app*
echo "appgen-select-${__APPGEN_PROFILE_API__}-${__APPGEN_PROFILE_FE__}" > appgen-select
chmod +x ./app*
