#!/usr/bin/env bash

(return 0 2>/dev/null) || { echo "$0: must be sourced"; exit 1; }

try () {
    "$@" || return 1
}

FATAL_FILE="./fatal.txt"
[ -f $FATAL_FILE ] && cat $FATAL_FILE && return 1

. appgen-activate

PROJECT_SRC="$__APPGEN_CMD_PATH__"
[ ! -d "$PROJECT_SRC" ] && echo "missing $PROJECT_SRC" > "$FATAL_FILE" && cat "$FATAL_FILE" && return 1

export APPGEN_PROJECT_NAME=${PWD##*/}

cp -R "${PROJECT_SRC}"/components/app/* .
echo "NAME=${APPGEN_PROJECT_NAME}" > ./docker/.env
chmod +x ./docker/*
chmod +x ./tmux/*

echo "echo ${APPGEN_PROJECT_NAME}" > app-name
chmod +x ./app*
[ -f ./mise.toml ] && mise trust mise.toml

OPT_QUIET="--quiet"

try db-init "$OPT_QUIET"
try db-new "$OPT_QUIET"

try api-init "$OPT_QUIET"
try api-new "$OPT_QUIET"

try ui-init "$OPT_QUIET"
try ui-new "$OPT_QUIET"
try ui-customize "$OPT_QUIET" # 2-phase ui creation/customization
