#!/usr/bin/env bash

THIS_DIR="${0%/*}"
DB_NAME=$("${THIS_DIR}"/database-name)

exec_psql() {
    docker exec -it "${DB_NAME}" psql -U postgres -f "./database/${1}"
}

# ----------------------------------------------------------------------------

