#!/usr/bin/env python

import env

import app.check_fields_option_csv as check_fields_option_csv
import tasks.db.db_csv_analyse_id_ref_strict as db_csv_analyse_id_ref_strict
import db.generate_ddl_sql as generate_ddl_sql
import tasks.db.db_sql_generate_dqml as db_sql_generate_dqml
import app.generate_csv as generate_csv
import tasks.api.generate_be4fe as generate_be4fe
import app.project_show_completed_tasks as project_show_completed_tasks

import app.project_check_user_actions as project_check_user_actions
import app.project_summary_entity_names as project_summary_entity_names
import app.project_summary_analysis as project_summary_analysis
import app.project_summary_sql as project_summary_sql

##############################################################################

ctx = env.create(__file__)
ctx.exec(ctx.set_entity_names_path_snake())
ctx.exec(check_entity_fields_option)
ctx.exec(db_csv_analyse_id_ref_strict)
ctx.exec(db_sql_generate_ddl)  # IMPORTANT! sql must be generated first
ctx.exec(db_sql_generate_dqml)
ctx.exec(db_csv_generate)
ctx.exec(generate_be4fe)
ctx.set_opt("--quiet", False)
ctx.exec(project_show_completed_tasks)

##############################################################################

# ctx.exec(project_check_user_actions)
# ctx.exec(project_summary_entity_names)
# ctx.exec(project_summary_analysis)
# ctx.exec(project_summary_sql)
