#!/usr/bin/env python

import env
import tasks.copy_db_seed_template_files as copy_db_seed_template_files

##############################################################################

ctx = env.create(__file__)
ctx.exec(copy_db_seed_template_files)

##############################################################################
