#!/usr/bin/env python

import env
import tasks.copy_db_seed_template_files as copy_db_seed_template_files
import postgres.tasks.analyse_csv_create_table_models as analyse_csv_create_table_models
import common.tasks.generate_schema as generate_schema
import common.tasks.generate_csv as generate_csv
import postgres.tasks.generate_ddl_sql as generate_ddl_sql
import common.tasks.project_show_completed_tasks as project_show_completed_tasks

import common.tasks.project_check_user_actions as project_check_user_actions
import common.tasks.project_summary_entity_names as project_summary_entity_names
import common.tasks.project_summary_analysis as project_summary_analysis
import common.tasks.project_summary_sql as project_summary_sql

# ##############################################################################

ctx = env.create(__file__)
ctx.set_entity_names_url_pascal()
ctx.exec(copy_db_seed_template_files)
ctx.exec(analyse_csv_create_table_models)
ctx.exec(generate_schema)
ctx.exec(generate_csv)
ctx.exec(generate_ddl_sql)
ctx.set_opt("--quiet", False)
ctx.exec(project_show_completed_tasks)

##############################################################################

# ctx.exec(project_check_user_actions)
# ctx.exec(project_summary_entity_names)
# ctx.exec(project_summary_analysis)
# ctx.exec(project_summary_sql)
