#!/usr/bin/env bash

FATAL_FILE="./fatal.txt"
[ -f $FATAL_FILE ] && cat $FATAL_FILE && exit 1

mkdir -p ./backend/api
cd ./backend/api || exit

[ -d node_modules ] && echo "$0: found node_modules, skipping" && exit

mise trust ./mise.toml
mise install

mise r npm init -y
mise r npm pkg set main="./src/index.js"
mise r npm pkg set scripts.api="nodemon ./src/index.js"
mise r npm pkg set scripts.docs="node ./src/swagger-autogen.js"
mise r npm pkg set scripts.start="npm run docs && npm run api"

mise r npm install --verbose express
mise r npm install --verbose swagger-ui-express
mise r npm install --verbose swagger-autogen
mise r npm install --verbose pg
mise r npm install --verbose cors

mise r npm install --verbose -D nodemon
