#!/usr/bin/env python

import set_paths
import express_js_postgres.backend_context as context
import postgres.tasks.analyse_csv_create_table_models as analyse_csv_create_table_models
import common.tasks.generate_csv as generate_csv
import common.tasks.generate_schema as generate_schema
import common.tasks.parse_schema as parse_schema
import postgres.tasks.generate_ddl_sql as generate_ddl_sql
import postgres.tasks.generate_dqml_sql as generate_dqml_sql
import express_js_postgres.tasks.api_generate_crud as generate_crud
import common.tasks.project_show_completed_tasks as project_show_completed_tasks

import common.tasks.project_check_user_actions as project_check_user_actions
import common.tasks.project_summary_entity_names as project_summary_entity_names
import common.tasks.project_summary_analysis as project_summary_analysis
import common.tasks.project_summary_sql as project_summary_sql

##############################################################################

ctx = context.create(__file__)
ctx.set_entity_names_url_pascal()
ctx.exec(analyse_csv_create_table_models)
ctx.exec(generate_csv)
ctx.exec(generate_schema)
ctx.exec(parse_schema)
ctx.exec(generate_ddl_sql)  # IMPORTANT! sql must be generated first
ctx.exec(generate_dqml_sql)
ctx.exec(generate_crud)
ctx.set_opt("--quiet", False)
ctx.exec(project_show_completed_tasks)

##############################################################################

# ctx.exec(project_check_user_actions)
# ctx.exec(project_summary_entity_names)
# ctx.exec(project_summary_analysis)
# ctx.exec(project_summary_sql)
