#!/usr/bin/env bash

try () {
    [ -f fatal.txt ] && cat fatal.txt && exit 1
    "$@" || exit 1
}

try . appgen
SCHEMA_DIR="${0%/*}/schema_json"

# ensure seed data can be found
"./${0%/*}/generate-schema"

# backend/api
# - generate API endpoint(s)
try api-endpoint-crud-schema "${SCHEMA_DIR}/tasks.json"

# frontend
# - generate page(s) using schema
try app-page-table-crud-schema "${SCHEMA_DIR}/tasks.json"

# amend menu item(s)
try app-menu-add --menu=Tasks
# app-menu-remove --menu=Home

# create db table(s) and seed them (allow time for db to become available)
try ./docker/db-start
echo "waiting for database..."
sleep 10s
try ./docker/db-seed
try ./docker/db-stop

echo
echo "app configured"
echo "./docker/app-start"
echo "./app-start"
echo "http://localhost:4200"
echo "http://localhost:3000/api-docs"
