#!/usr/bin/env bash

is_invalid=0
is_sourced=1
(return 0 2>/dev/null) || { is_sourced=0; }

check_valid() {
    [ -z "${2}" ] && echo "EMPTY ${1}" && is_invalid=1 && return
    [ ! -d "${2}" ] && echo "INVALID FOLDER $1: ${2}" && is_invalid=1
}

check_valid __APPGEN_HOME__ "$__APPGEN_HOME__"
check_valid __APPGEN_CMD_PATH__ "$__APPGEN_CMD_PATH__"
check_valid __APPGEN_DB_PATH__ "$__APPGEN_DB_PATH__"
check_valid __APPGEN_DB_CMD_PATH__ "$__APPGEN_DB_CMD_PATH__"
check_valid __APPGEN_API_PATH__ "$__APPGEN_API_PATH__"
check_valid __APPGEN_API_CMD_PATH__ "$__APPGEN_API_CMD_PATH__"
check_valid __APPGEN_FE_PATH__ "$__APPGEN_FE_PATH__"
check_valid __APPGEN_FE_PATH__ "$__APPGEN_FE_PATH__"

if [ $is_invalid -eq 1 ]; then
    echo "INVALID appgen environment - select using '. appgen-select-*'"
    [ $is_sourced -eq 1 ] && return 1
    exit 1
fi

echo "APPGEN_HOME=${__APPGEN_HOME__}"
echo "DB=${__APPGEN_PROFILE_DB__}"
echo "API=${__APPGEN_PROFILE_API__}"
echo "FE=${__APPGEN_PROFILE_FE__}"
echo "appgen-select: appgen-select-${__APPGEN_PROFILE_API__}-${__APPGEN_PROFILE_FE__}"

FATAL_FILE="./fatal.txt"

if [ -f $FATAL_FILE ]; then
    cat $FATAL_FILE
    [ $is_sourced -eq 1 ] && return 1
    exit 1
fi
