#!/usr/bin/env bash

appgen-info || exit

try () {
    "$@" || return 1
}

OPT_QUIET="--quiet"

try app-init "$OPT_QUIET"
try app-new "$OPT_QUIET"

try db-init "$OPT_QUIET"
try db-new "$OPT_QUIET"

try api-init "$OPT_QUIET"
try api-new "$OPT_QUIET"

try ui-init "$OPT_QUIET"
try ui-new "$OPT_QUIET"
try ui-customize "$OPT_QUIET" # 2-phase ui creation/customization
