#!/usr/bin/env bash

appgen-info || exit

[ ! -f "./_app_name" ] && echo "missing file: ./_app_name" > "$FATAL_FILE" && cat "$FATAL_FILE" && exit 1
DB_NAME=$(./_app_name)"-database-1"

mkdir -p ./backend/database/scripts

echo "echo ${DB_NAME}" > ./backend/database/scripts/_db_name
chmod +x ./backend/database/scripts/_db_name

echo "**/db_data" > .gitignore

echo "configured database folders"
