#!/usr/bin/env bash

FATAL_FILE="./fatal.txt"
[ -f $FATAL_FILE ] && cat $FATAL_FILE && exit 1

[ ! -f "./app-name" ] && echo "missing file: ./app-name" > "$FATAL_FILE" && cat "$FATAL_FILE" && exit 1
DB_NAME=$(./app-name)"-database-1"

mkdir -p ./backend/database/scripts

echo "echo ${DB_NAME}" > ./backend/database/scripts/database-name
chmod +x ./backend/database/scripts/database-name

echo "**/db_data" > .gitignore

echo "configured database folders"