#!/usr/bin/env bash

THIS_DIR="${0%/*}"
DB_NAME=$("${THIS_DIR}"/_db_name)

CSV_SEED_DIR="./database/csv_seed"

echo "load: ${CSV_SEED_DIR}/__ENTITY_SNAKE__.csv => __ENTITY_SNAKE__"

docker exec -it "${DB_NAME}" psql -U postgres -c "\copy __ENTITY_SNAKE__ \
(__ENTITY_COLUMNS__) \
from ${CSV_SEED_DIR}/__ENTITY_SNAKE__.csv delimiter ',' csv header;"
